# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
use_bioc: true
bioc_required: true
r:
  - bioc-release
  - bioc-devel
  - oldrel
  - release
  - devel

r_packages:
  - devtools

sudo: true
cache: packages

notifications:
  email:
    recipients:
      - gabriel.odom@med.miami.edu
