# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

notifications:
  email:
    recipients:
      - gabriel_odom@baylor.edu
      - gabriel.odom@med.miami.edu
